### ISSUE TITLE
LSM9DS1 driver configuring as I2C bus

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [STMicroelectronics/STMems_Linux_Input_drivers#3]
Hi, 
I want to update the device tree for LSM9DS1, is below configuration correct -  
  &i2c0 {
  	status = "ok";
  	#address-cells = <0x1>;
  	#size-cells = <0x0>;
  	lsm6dsm@6b {
  		compatible = "st,lsm9ds1";
  		reg = <0x6b>;
  		interrupt-parent = <&gpio>;
  		interrupts = <26 IRQ_TYPE_EDGE_RISING>;
  };

I am want to use the module this module with PI-  https://store.digilentinc.com/pmod-nav-9-axis-imu-plus-barometer/

**Comment by mariotesi** [comment]
Not sure for PI, in any case generally is something like that

for I2C interface :
        lsm9ds1_acc_gyr@6b {
                pinctrl-names = "default";
                compatible = "st,lsm9ds1_acc_gyr";
                reg = <0x6b>;
                rot-matrix = /bits/ 16 <(1) (0) (0)
                             (0) (1) (0)
                             (0) (0) (1)>;
                g-poll-interval = <100>;
                g-min-interval = <2>;
                g-fs-range = <0>;
                x-poll-interval = <100>;
                x-min-interval = <1>;
                x-fs-range = <0>;
                aa-filter-bw = <0>;
                interrupt-parent = <&gpio>;
                interrupts = <26 1>;
                status = "ok";
        };

        lsm9ds1_mag@1e {
                pinctrl-names = "default";
                compatible = "st,lsm9ds1_mag";
                reg = <0x1e>;
                rot-matrix = /bits/ 16 <(1) (0) (0)
                             (0) (1) (0)
                             (0) (0) (1)>;
                poll-interval = <100>;
                min-interval = <13>;
                fs-range = <0>;
                status = "ok";
        };

and for SPI interface:
        lsm9ds1_acc_gyr@2 {
                pinctrl-names = "default";
                compatible = "st,lsm9ds1_acc_gyr";
                spi-max-frequency = <2000000>;
                reg = <2>;
                rot-matrix = /bits/ 16 <(1) (0) (0)
                             (0) (1) (0)
                             (0) (0) (1)>;
                g-poll-interval = <100>;
                g-min-interval = <2>;
                g-fs-range = <0>;
                x-poll-interval = <100>;
                x-min-interval = <1>;
                x-fs-range = <0>;
                aa-filter-bw = <0>;
                interrupt-parent = <&gpio>;
                interrupts = <26 1>;
                status = "ok";
        };

        lsm9ds1_mag@1 {
                pinctrl-names = "default";
                compatible = "st,lsm9ds1_mag";
                spi-max-frequency = <2000000>;
                reg = <1>;
                rot-matrix = /bits/ 16 <(1) (0) (0)
                             (0) (1) (0)
                             (0) (0) (1)>;
                poll-interval = <100>;
                min-interval = <13>;
                fs-range = <0>;
                status = "ok";
        };

consider that the Pmod NAV use only SPI interface ..... so you have to use two separate SPI interface and related CS
You need also customize the interrupts and interrupt-parent for your specific target board (Raspberry, HiKey etc. etc. please see GPIO and interrupt routing four your selected board)

**Comment by ShettyHarapanahalli** [comment]
Thanks for the same.
