### ISSUE TITLE
regarding device tree configuration

### ISSUE THREAD

**Issue by Meera0212** [STMicroelectronics/STMems_Linux_Input_drivers#4]
I can't understand at which location I'm getting device tree file and where i need to add lsm6dsm node for I2C/SPI digital interface support.

**Comment by mariotesi** [comment]
Hi,

The file position depends on your target architecture, for examples for Raspberry PI 3 the relative path is arch/arm/boot/dts

Typically device tree files for ARM processors are positioned in arch/arm if target is ARM 32 bits and arch/arm64 if target is ARM 64 bit

The point at which to add sensor support in the device tree files strongly depends on the architecture of your target board, the type and number of the interface to which it is connected (for example i2c 0 or i2c 1 or SPI 0 and so on) the LSM6DSM

I recommend you to consult the documentation of your target system for more info as device tree configuration it is very related to the board you are using
